config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  
  # Recreates the Devise registrations routes
  # They act on a singular user (the signed in user)
  # Add the actions you want in 'only:'
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
      get 'cancel'
    end
  end

    authenticated :user do   
      # Seting up admin scope for :users
      # so as to not conflict with the routes from devise.
      # These routes should give users with the admin role
      # the abbility to edit info for all other users.
      scope "/admin" do
        resources :users do
        end
      end
      
      resources :volunteers do
      end
    
      resources :groups do
        # member do
        #   get 'print'
        # end
        collection do
          post 'update_kid_assignment'
          post 'update_volunteer_assignment'
          get 'print_sign_outs'
        end
      end
      
      resources :kids do
        get 'register', on: :new
        collection do
          post 'confirm'
          get 'print_all_kids'
        end
      end

      resources :locations do
        collection do
          post 'update_volunteer_assignment'
        end
      end

      root to: 'kids#index', as: :authenticated_root
    end
  

    root to: redirect('users/sign_in')
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  include PgSearch
  belongs_to :leader, polymorphic: true, optional: true

  pg_search_scope :search_for, against: %i(first_name last_name)

  scope :sort_by_last_name, -> { order( last_name: :asc ) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def index
    if params[:term]
      @volunteers = Volunteer.search_for(params[:term])
    else
      @volunteers = Volunteer.all
    end
  end

  def new
    @volunteer = Volunteer.new
  end

  def edit
    @volunteer = Volunteer.find(params[:id])
  end

  def destroy
    Volunteer.find(params[:id]).destroy
    flash[:success] = "Volunteer removed"
    redirect_to volunteers_path
  end
  
  def show
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
  
  def create
    @volunteer = Volunteer.create(volunteer_params)
    if @volunteer.save
      flash[:success] = "<strong>#{@volunteer.first_name} #{@volunteer.last_name}</strong> was successfully added"
      redirect_to volunteers_path
    else
      flash.now[:warning] = "Something went wrong"
      render 'new'
    end
  end

  def update
    @volunteer = Volunteer.find(params[:id])
    if @volunteer.update_attributes(volunteer_params)
      flash[:success] = "<strong>#{@volunteer.first_name} #{@volunteer.last_name}</strong> was successfully updated"
      redirect_to volunteers_path
    else
      flash.now[:warning] = "Something went wrong"
      render 'edit'
    end
  end
  

  private
  def volunteer_params
    params.require(:volunteer).permit(:first_name,
                                      :last_name,
                                      :email,
                                      :phone,
                                      :notes,
                                      :leader_type,
                                      :leader_id)
  end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= form_for @volunteer do | f | %>
<div class="form-inline">
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</div>

<div class="form-inline">
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>

<div class="form-inline">
    <%= f.label :email %>
    <%= f.text_field :email %>
</div>

<div class="form-inline">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
</div>

<div class="form-inline">
  <%= f.label :notes %>
  <%= f.text_area :notes %>
</div>

  <div class="custom-controls-stacked">
    <legend>Assignment</legend>
    <label class="custom-control custom-radio">
      <%= f.radio_button :leader_type, :Group, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Class</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button :leader_type, :Location, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Station</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button :leader_type, :none, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Unassigned</span>
    </label>
</div>
<div class="form-group">
  <%= f.collection_select :leader_id, Group.sort_by_grade.sort_by_name.all, :id, :name_grade, {prompt: 'Select assignment', include_blank: 'Unassigned'}, class: "custom-select"%>
  </div>
<%= f.submit "Save", date: {"disable-with": "Saving..."}, class: "btn btn-primary" %>
<% end %>

app/views/volunteers/edit.html.erb
<%= render partial: "form", locals: {volunteer: @volunteer} %>

app/views/volunteers/index.html.erb
<div class="container w-100">
  
   <div class="row justify-content-center">
    <div class="col">
      <h1>Volunteers</h1>
    </div>
    <div class="col-6">
      <%= form_tag(volunteers_path, method: :get, class: "input-group") do %>
      <%= text_field_tag :term, params[:term], placeholder: "Search for...", class: "form-control" %>
      <span class="input-group-btn">
        <%= button_tag 'Search', class: "btn btn-secondary" %>
      </span>
      <% end %>
    </div>
   </div>
   <div class="row">
     <div class="col-sm-3">
       <h5>Total Volunteers: <strong><%= @volunteers.count %></strong></h5>
       </div>
   </div>
  
  <div class="row justify-content-center mt-4">
    
    <div class="col-lg-12 mb-3 ml-4">
      <a class="btn btn-primary btn-sm" href="<%= new_volunteer_path %>">Add New</a>
      <a class="btn btn-outline btn-sm" href="<% %>">Print</a>
    </div>
    <div class="col-xl-12">
      <table class="table table-sm table-hover">
	<thead>
	  <tr>
	    <th></th>
	    <th>Name</th>
	    <th>Assignment</th>
	    <th>Notes</th> <!-- this is for the notes icon which will have a pop over on hover -->
	    <th>Phone</th>
	    <th>Email</th>
	    <th></th> <!-- Column for edit link -->
	  </tr>
	</thead>
	
	<tbody>
	  <% @volunteers.sort_by_last_name.each do |volunteer| %>
	  <tr>
	    <td></td>
	    <td onclick="window.location='<%= volunteer_path(volunteer)%>';" style='cursor: pointer;'><%= "#{volunteer.first_name} #{volunteer.last_name}" %></td>
	    <% if volunteer.leader_type == "Group" %>
	      <% if volunteer.leader_id == nil %>
	      <td>Class</td>
	      <% else %>
	      <td><%= "#{volunteer.leader.name_grade}" %></td>
	      <% end %>
	    <% elsif volunteer.leader_type == "Location" %>
	      <% if volunteer.leader_id == nil %>
	      <td>Station</td>
	      <% else %>
	      <td><%= "#{volunteer.leader.name}" %></td>
	      <% end %>
	      <% elsif volunteer.leader_type == "Team" %>
	      <% if volunteer.leader_id == nil %>
	      <td>Station</td>
	      <% else %>
	      <td><%= "#{volunteer.leader.name}" %></td>
	      <% end %>
	    <% elsif volunteer.leader_type == "none" %>
	    <td>--</td>
	    <% end %>
	    <td></td>
	    <td><%= "#{volunteer.phone}" %></td>
	    <td><%= "#{volunteer.email}" %></td>
	    <td><%= link_to "Edit", edit_volunteer_path(volunteer) %></td>
	  </tr>
	  <% end %>
	</tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/volunteers/new.html.erb
<%= render partial: "form", locals: {volunteer: @volunteer}  %>

app/views/volunteers/show.html.erb
<br>
<div class="container w-75">
  <div class="card">
    <div class="card-header">
      <nav class="nav nav-pills card-header-pills">
	<a class="nav-link active" href="<%= edit_volunteer_path(@volunteer.id) %>">Edit</a>
	<a class="nav-link" href="#">Print</a>
	<a class="nav-link" href="#">Locate</a>
	<%= link_to "Delete", @volunteer, method: :delete, class: "nav-link", data: {confirm: "Are you sure?" } %>
      </nav>
    </div>
    <div class="card-block">
      <h1 class="card-title"><%= @volunteer.first_name %> <%= @volunteer.last_name %></h1>
      <hr>
      <h4><%= @volunteer.phone %></h4>
      <h4><%= @volunteer.email %></h4>
      <div class="row">
	<h5 class="col-md-2">Notes:</h5>
	<p class="col-md-4"><%= @volunteer.notes %></p>
      </div>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last Updated <%= @volunteer.updated_at.to_time.strftime('%B %e at %l:%M %p') %></small>
    </div>
  </div>
</div>