config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  
  # Recreates the Devise registrations routes
  # They act on a singular user (the signed in user)
  # Add the actions you want in 'only:'
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
      get 'cancel'
    end
  end

    authenticated :user do   
      # Seting up admin scope for :users
      # so as to not conflict with the routes from devise.
      # These routes should give users with the admin role
      # the abbility to edit info for all other users.
      scope "/admin" do
        resources :users do
        end
      end
      
      resources :volunteers do
      end
    
      resources :groups do
        # member do
        #   get 'print'
        # end
        collection do
          post 'update_kid_assignment'
          post 'update_volunteer_assignment'
          get 'print_sign_outs'
        end
      end
      
      resources :kids do
        get 'register', on: :new
        collection do
          post 'confirm'
          get 'print_all_kids'
        end
      end

      resources :locations do
        collection do
          post 'update_volunteer_assignment'
        end
      end

      root to: 'kids#index', as: :authenticated_root
    end
  

    root to: redirect('users/sign_in')
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kid.rb
class Kid < ApplicationRecord
  include PgSearch
  
  belongs_to :group, optional: true

  pg_search_scope :search_for, against: %i(first_name last_name)
  pg_search_scope :search_grades, against: %i(last_grade_id)
  
  scope :sort_by_last_name, -> { order( last_name: :asc ) }
  scope :sort_by_grade, -> { order( last_grade_id: :asc ) }
  
  validates :first_name, :last_name, presence: true

  validates :birthdate, presence: true

  validates :gender, presence: true
  
  validates :address, :city, :zipcode, presence: true
  validates :state, presence: true
  validates :parent_name, presence: true
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :parent_email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }

  #TODO: we will need to make sure this is a valid phone number
  validates :parent_phone, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def current_grade
    lg = self.last_grade_id
    if lg == 8
      return "7th"
    else
      return "#{Kid.grade_types.at(lg + 1)}"
    end
  end

  def self.grade_types
    ["Pre-K", "4k", "5k", "1st", "2nd", "3rd", "4th", "5th", "6th"]
  end

  def grade
    lg = self.last_grade_id
    return "#{Kid.grade_types.at(lg)}"
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  helper ApplicationHelper
  
  def index
    if params[:term]
      @kids = Kid.search_for(params[:term])
    elsif params[:grade]
      @kids = Kid.search_grades(params[:grade])
    else
      @kids = Kid.all
    end      
  end

  def print_all_kids
    @kids = Kid.where(church_member: false)

    respond_to do |format|
      format.html
      format.pdf do
      end
      format.xls { response.headers["Content-Disposition"] = "attachment; filename=\"Sign-out-sheets.xml\"" }
    end
  end

  #These methods are for working with kids from the volunteer context
  def new
    @kid = Kid.new
  end
  
  def edit
    @kid = Kid.find(params[:id])
  end

  def destroy
    Kid.find(params[:id]).destroy
    flash[:success] = "Kid removed"
    redirect_to kids_path
  end

  def update
    @kid = Kid.find(params[:id])
    if @kid.update_attributes(kid_params)
      flash[:success] = "<strong>#{@kid.first_name} #{@kid.last_name}</strong> was successfuly updated"
      redirect_to kids_path
    else
      flash.now[:warning] = "Something went wrong"
      render 'edit'
    end
  end
  
  def create
    @kid = Kid.create(kid_params)
    if @kid.save
      flash[:success] = "<strong>#{@kid.first_name} #{@kid.last_name}</strong> was successfully registerd"
      redirect_to kids_path
    else
      flash.now[:warning] = "Something went wrong"
      render 'new'
    end
  end
  
  def show
    @kid = Kid.find(params[:id])
  end
  #These methods are for working with kids from the registration perspective
  def register
    #Call render the fancy registration form
    @kid = Kid.new
    render layout: "public"
  end
  
  def confirm
    @kid = Kid.create(kid_params)
    if @kid.save
      render layout: "public"
    else
      flash.now[:warning] = "something went wrong"
      render 'register'
    end
  end
  
  private
  
  def kid_params
    params.require(:kid).permit(:first_name,
                                :last_name,
                                :birthdate,
                                :last_grade_id,
                                :gender,
                                :address,
                                :city,
                                :state,
                                :zipcode,
                                :parent_name,
                                :parent_email,
                                :parent_phone,
                                :church_member,
                                :invited_by,
                                :tshirt_size_id,
                                :allergies,
                                :allergies_notes,
                                :medical_issues,
                                :medical_issues_notes,
                                :buddy_request,
                                :notes,
                                :pickupper_1_name,
                                :pickupper_1_phone,
                                :pickupper_2_name,
                                :pickupper_2_phone,
                                :pickupper_3_name,
                                :pickupper_3_phone,
                                :highlight,
                                :can_photograph,
                                :group_id,
                                :term,
                                :grade)
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_errors.html.erb
<% if @kid.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>
 
    <ul>
    <% @kid.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/kids/_kid_form.html.erb
<hr>
<h3>Child Info</h3>
<hr>
<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Name</label>
  <div class="col-sm-4">
    <%= f.text_field :first_name, class: "form-control" %>
    <small class="form-text text-muted">First Name</small>
  </div>
  <div class="col-sm-4">
    <%= f.text_field :last_name, class: "form-control" %>
    <small class="form-text text-muted">Last Name</small>
  </div>
</div>

<div class="form-group row">
  <!-- <label class="col-sm-2 text-sm-right col-form-label">Gender</label> -->
  <div class="col-sm-8 offset-md-3">
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, :male, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Male</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, :female, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Female</span>
    </label>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 text-sm-right col-form-label">Birthday</label>
  <div class="col-sm-8">
    <%= f.date_select :birthdate, { :start_year => 2004, :end_year => 2017, :prompt => { day: 'Day', month: 'Month', year: 'Year' }, :use_short_month => true, :order => [:day, :month, :year]}, class: "custom-select" %>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 text-sm-right col-form-label">Last Grade Completed</label>
  <div class="col-sm-8">
    <%= f.select :last_grade_id, grade_types.map.with_index{ |s, i| [s, i]}, {}, {class: "custom-select"}  %>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-3 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :church_member, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Regular Attendee</span>
    </label>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Invited By</label>
  <div class="col-sm-8 ">
    <%= f.text_field :invited_by, class: "form-control" %>
    <small class="form-text text-muted">If you were invited by a member of Brushy Creek please give their name.</small>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Class Buddy</label>
  <div class="col-sm-8">
    <%= f.text_field :buddy_request, class: "form-control" %>
    <small class="form-text text-muted">If you would like your child to be in a class woth a specific friend please give their name and we make every effort to place them together..</small>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-8 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :can_photograph, checked: true, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Can be photographed</span>
    </label>
    <small class="form-text text-muted">Is your child allowed to be inclueded in photographs or videos relating to VBS.</small>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-8 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :allergies, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Allergies</span>
    </label>
  </div>
  <div class="col-sm-8 offset-md-3">
    <%= f.text_area :allergies_notes, placeholder: "Alergies, Epipen, etc.",  class: "form-control"%>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-6 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :medical_issues, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Other Medical Issues</span>
    </label>
  </div>
  <div class="col-sm-8 offset-md-3">
    <%= f.text_area :medical_issues_notes, placeholder: "Bloody Noses, etc.",  class: "form-control"%>
  </div>
</div>

<hr>
<h3>Parent/Guardian Info</h3>
<hr>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Name</label>
  <div class="col-sm-8">
    <%= f.text_field :parent_name, class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Email</label>
  <div class="col-sm-8">
    <%= f.text_field :parent_email,type: "eamil", class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Phone Number</label>
  <div class="col-sm-8">
    <%= f.text_field :parent_phone, type: "tel", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <label class="col-sm-3 text-sm-right col-form-label">Address</label>
    <div class="col-sm-8">
      <%= f.text_field :address, class: "form-control" %>
      <small class="form-text text-muted">Street</small>
    </div>
  </div>
  <div class="row">
    <div class="col-3 offset-md-3">
      <%= f.text_field :city, class: "form-control" %>
      <small class="form-text text-muted">City</small>
    </div>
    <div class="col-2">
      <%= f.select :state, CS.states(:us),{}, class: "custom-select w-100"%>
      <small class="form-text text-muted">State</small>
    </div>
    <div class="col-3">
      <%= f.text_field :zipcode, class: "form-control" %>
      <small class="form-text text-muted">Zipcode</small>
    </div>
  </div>
</div>

<hr>
<h3>Pickup/Emergency Contacts</h3>
<p>Additonal people we can contact in an emergency. They are also authorized to sign your child out.</p>
<hr>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Contact 1</label>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_1_name, class: "form-control" %>
    <small class="from-text text-muted">Name</small>
  </div>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_1_phone, type: "tel", class: "form-control" %>
    <small class="from-text text-muted">Phone Number</small>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Contact 2</label>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_2_name, class: "form-control" %>
    <small class="from-text text-muted">Name</small>
  </div>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_2_phone, type: "tel", class: "form-control" %>
    <small class="from-text text-muted">Phone Number</small>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Contact 3</label>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_3_name, class: "form-control" %>
    <small class="from-text text-muted">Name</small>
  </div>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_3_phone, type: "tel", class: "form-control" %>
    <small class="from-text text-muted">Phone Number</small>
  </div>
</div>

<% if edit == 1 %>
<div id="admin-kid-form" class="jumbotron">
  <div class="container">
    <hr>
    <h3>Admin Only</h3>
    <hr>

    <div class="form-group row">
      <div class="col-sm-8 offset-md-3">
	<label class="custom-control custom-checkbox">
	  <%= f.check_box :highlight, class: "custom-control-input" %>
	  <span class="custom-control-indicator"></span>
	  <span class="custom-control-description">Highlight</span>
	</label>
	<small class="form-text text-muted">Add a highlight when the kid is displayed on other pages</small>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 text-sm-right col-form-label">Notes</label>
      <div class="col-sm-8">
	<%= f.text_area :notes, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-3 text-sm-right col-form-label">Assign to class</label>
      <div class="col-sm-8">
	<%= f.collection_select :group_id, Group.sort_by_grade.sort_by_name.all, :id, :name_grade, {include_blank: 'Unassigned'}, class: "custom-select"%>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/kids/confirm.html.erb
<div class="jumbotron">
  <h1>Thank you for registering for <strong>Under Contruction</strong>!</h1>
  <br>
   <%= link_to "The registration volunteer will help you complete the process. ", edit_kid_path(@kid) %>
</div>
      

app/views/kids/edit.html.erb
<%= content_for :title do %>
Edit <%= @kid.first_name %>'s Registration
<% end %>

<div class="container">
  <%= render partial: "errors", locals: {kid: @kid} %>
  <%= form_for @kid do |f| %>
  <%= render partial: "kid_form", locals: {kid: @kid, edit: 1, f: f} %>
  <br>
  <div class="row">
    <div class="col-sm-6 offset-3">
      <%= f.submit "Save", data: {"disable_with":"Saving..."}, class: "btn btn-primary"%>
    </div>
  </div>
  <% end %>
</div>

app/views/kids/index.html.erb
<% content_for :title do %>
Kids Inbox
<% end %>

<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col">
	<a class="btn btn-secondary btn-lg btn-block" href="<%= register_new_kid_path %>" >New In-Person Registration</a>
      </div>
    </div>
  </div>
</div>

<div class="container w-100">
  
  <div class="row justify-content-center">
    <div class="col">
      <h1>Registrations</h1>
    </div>
    <div class="col-6">
      <%= form_tag(kids_path, method: :get, class: "input-group") do %>
      <%= text_field_tag :term, params[:term], placeholder: "Search for...", class: "form-control" %>
      <span class="input-group-btn">
        <%= button_tag 'Search', class: "btn btn-secondary" %>
      </span>
      <% end %>
    </div>
  </div>
     <div class="row">
     <div class="col-sm-3">
       <h5>Total Kids: <strong><%= @kids.count %></strong></h5>
       <h5>Regualar Attendees: <strong><%= @kids.where(church_member: true).count %></strong></h5>
       <h5>Guest: <strong><%= @kids.where(church_member: false).count %></strong></h5>
       </div>
   </div>
  
  <div class="row justify-content-center mt-4">
    
    <div class="col-lg-12 mb-3 ml-4">
      <a class="btn btn-primary btn-sm" href="<%= new_kid_path %>">Add New</a>
      <a class="btn btn-secondary btn-sm" href="<%= print_all_kids_kids_path(format: :pdf)  %>">Print Visitors</a>
      |
      <div class="btn-group">
	<%= link_to "Pre-k", kids_path(grade: "0"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "4k", kids_path(grade: "1"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "5k", kids_path(grade: "2"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "1st", kids_path(grade: "3"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "2nd", kids_path(grade: "4"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "3rd", kids_path(grade: "5"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "4th", kids_path(grade: "6"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "5th", kids_path(grade: "7"), type: "button", class: "btn btn-outline-primary btn-sm" %>
	<%= link_to "6th", kids_path(grade: "8"), type: "button", class: "btn btn-outline-primary btn-sm" %>
      </div>
      </div>
    <div class="col-xl-12">
      <table class="table table-sm table-hover">
	<thead>
	  <tr>
	    <th></th>
	    <th>Name</th>
	    <th>Age</th>
	    <th>Grade</th> <!-- this will deisplay the grade the kid will be going to next year -->
	    <th>Class</th>
	    <th>Notes</th> <!-- this is for the notes icon which will have a pop over on hover -->
	    <th>Medical</th> <!-- this is for the meidal alerts icons -->
	    <th></th>
	  </tr>
	</thead>
	
	<tbody>
	  <% @kids.sort_by_last_name.each do |kid| %>
	  <% if kid.highlight %>	
	  <tr class="table-warning">
	  <% else %>
	  <tr>
	  <% end %>
	  <td class="text-right">
	    <% unless kid.can_photograph %>
	      <i class="fa fa-camera text-danger"></i>
	    <% end %>
	  </td>
	  <td onclick="window.location='<%= kid_path(kid)%>';" style='cursor: pointer;'><%= "#{kid.first_name} #{kid.last_name}" %>
	    <% unless kid.buddy_request.empty? %>
	    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
	    <% end %>
	  </td>
	    <td><%= find_age(kid.birthdate) %></td>
	    <td><%= kid.grade %></td>
	    <td>
	      <% if kid.group.present? %>
	      <%= kid.group.name %>
	      <% else %>
	      --
	      <% end %>
	    </td>
	    <td>
	      <% if kid.notes.present? %>
	      <a tabindex="0" data-toggle="popover" data-trigger="focus"  data-content="<%= kid.notes %>">
		<i class="fa fa-comment" aria-hidden="true"></i>
	      </a>
	      <% end %>
	    </td>
	    <td>
	      <% if kid.allergies %>
	      <span class="badge badge-warning">Allergies</span>
	      <% end %>
	      <% if kid.medical_issues %>
	      <span class="badge badge-info">Other</span>
	      <% else %>
	      <% end %>
	    </td>
    </div>
    <td><%= link_to "Edit", edit_kid_path(kid) %></td>
    </tr>
    <% end %>
    </tbody>
    </table>
    </div>
  </div>
  
</div>

app/views/kids/new.html.erb
<% content_for :title do %>
New Registration
<% end %>

<div class="container">
  <h1>Register New Child </h1>
  <%= render partial: "errors", locals: {kid: @kid} %>
  <%= form_for @kid do |f| %>
  <%= render partial: "kid_form", locals: {kid: @kid, f: f, edit: 1} %>
  <br>
  <div class="row">
    <div class="col-sm-6 offset-md-3">
      <%= f.submit "Register", data: {"diable-with":"Saving..."}, class: "btn btn-primary"%>
    </div>
  </div>
  <% end %>

app/views/kids/register.html.erb
<% content_for :title do %>
Register Child
<% end %>

<div class="container w-75 bg-faded">
  <h1>Register New Child</h1>
  <%= render partial: "errors", locals: {kid: @kid} %>
  <%= form_for @kid, url: confirm_kids_path do |f| %>
  <%= render partial: "kid_form", locals: {kid: @kid, f: f, edit: 0} %>
  <br>
  <div class="row">
    <div class="col-sm-6 offset-3">
      <%= f.submit "Register", data: {"disable-with":"Saving..."}, class: "btn btn-primary"%>
    </div>
  </div>
  <% end %>

app/views/kids/show.html.erb
<br>
<div class="container w-75">
  <div class="card">
    <div class="card-header">
      <nav class="nav nav-pills card-header-pills">
	<a class="nav-link active" href="<%= edit_kid_path(@kid.id) %>">Edit</a>
	<% if @kid.group_id %>	
	<%= link_to "View Class", groups_path(anchor: "group-#{@kid.group_id}"), class: "nav-link"  %>
	<% end %>
	<a class="nav-link" href="#">Locate</a>
	<%= link_to "Delete", @kid, method: :delete, class: "nav-link", data: {confirm: "Are you sure?" } %>
      </nav>
    </div>
    <div class="card-block">
      <h1 class="card-title"><%= @kid.first_name %> <%= @kid.last_name %> <small class="text-muted"> | <%=find_age(@kid.birthdate) %> years old | <%= @kid.gender %>
	<% if !@kid.can_photograph %>
	<span class="fa-stack">
	  <i class="fa fa-camera fa-stack-1x"></i>
	  <i class="fa fa-ban fa-stack-2x text-danger"></i>
	</span>
	<% end %>
	</small>
      </h1>
      <hr>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Birthday:</h5>
	</div>
	<div class="col-4"> 
	  <p><%= pretty_print_date(@kid.birthdate) %></p>
	</div>
      </div>

      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Last Completed Grade:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.grade  %></p>
	</div>
      </div>
      <% if @kid.group_id %>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Class:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.group.name_grade  %></p>
	</div>
      </div>
      <% end %>
      <% unless @kid.buddy_request.empty? %>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Friend Request:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.buddy_request  %></p>
	</div>
      </div>
      <% end %>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Regular Attendee:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.church_member ? "Yes" : "No"  %></p>
	</div>
      </div>
      <% if !@kid.church_member %>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Invited By:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.invited_by %></p>
	</div>
      </div>
      <% end %>

      <% if @kid.allergies %>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Allergies:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.allergies_notes %></p>
	</div>
      </div>
      <% end %>
      <% if @kid.medical_issues %>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Medical Issues:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.medical_issues_notes %></p>
	</div>
      </div>
      <% end %>


      <div class="row">
	<div class="col-sm-4 offset-sm-2">
	  <h4>Parent Info</h4>
	  <hr>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Name:</h5>
	</div>
	<div class="col-sm-4">
	  <p><%= @kid.parent_name %></p>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Phone:</h5>
	</div>
	<div class="col-sm-4">
	  <p><%= @kid.parent_phone %></p>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Email:</h5>
	</div>
	<div class="col-sm-4">
	  <p><%= @kid.parent_email %></p>
	</div>
	</div>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Address:</h5>
	  </div>
	<address class="col-sm-6">
	  <%= @kid.address %><br>
	  <%= @kid.city %>, <%= @kid.state %> <%= @kid.zipcode %><br>
	</address>
      </div>
      <div class="row">
	<div class="col-sm-4 offset-sm-2">
	  <h4>Emergency Contacts and Pickup</h4>
	</div>
      </div>
      
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Contact 1:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.pickupper_1_name %> - <%= @kid.pickupper_1_phone %></p>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Contact 2:</h5>
	</div>
	<div class="col-4">
	  <p><%= @kid.pickupper_2_name %> - <%= @kid.pickupper_2_phone %></p>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-2 text-right">
	  <h5>Contact 3:<h5p>
	</div>
	<div class="col-4">
	  <p><%= @kid.pickupper_3_name %> - <%= @kid.pickupper_3_phone %></p>
	</div>
      </div>
      <% unless @kid.notes == nil %>
      <div class="row">
	<div class="col-sm-2 offset-sm-2">
	  <h4>Notes</h4>
	</div>
      </div>
      <div class="row">
	<div class="col-sm-6 offset-sm-2">
	  <p><%= @kid.notes %></p>
	</div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <small class="text-muted">Last Updated <%= @kid.updated_at.to_time.strftime('%B %e at %l:%M %p') %></small>
  </div>
</div>

	       