config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  
  # Recreates the Devise registrations routes
  # They act on a singular user (the signed in user)
  # Add the actions you want in 'only:'
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
      get 'cancel'
    end
  end

    authenticated :user do   
      # Seting up admin scope for :users
      # so as to not conflict with the routes from devise.
      # These routes should give users with the admin role
      # the abbility to edit info for all other users.
      scope "/admin" do
        resources :users do
        end
      end
      
      resources :volunteers do
      end
    
      resources :groups do
        # member do
        #   get 'print'
        # end
        collection do
          post 'update_kid_assignment'
          post 'update_volunteer_assignment'
          get 'print_sign_outs'
        end
      end
      
      resources :kids do
        get 'register', on: :new
        collection do
          post 'confirm'
          get 'print_all_kids'
        end
      end

      resources :locations do
        collection do
          post 'update_volunteer_assignment'
        end
      end

      root to: 'kids#index', as: :authenticated_root
    end
  

    root to: redirect('users/sign_in')
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :kids, dependent: :nullify
  has_many :volunteers, as: :leader, dependent: :nullify

  scope :sort_by_name, -> { order(name: :asc) }
  scope :sort_by_grade, -> { order(grade_id: :asc) }
  
  def name_grade
    grades = ["Pre-K", "4k", "5k", "1st", "2nd", "3rd", "4th", "5th", "6th & 7th"]

    "#{grades[grade_id]} - #{name}"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @unassigned_kids = Kid.where(group_id: nil).all
    @unassigned_leaders = Volunteer.where(leader_type: "Group").where(leader_id: nil).all
    @groups = Group.all
   
    respond_to do |format|
      format.html
      format.pdf
      format.xls { response.headers["Content-Disposition"] = "attachment; filename=\"Classes.xml\"" }
    end
  end

  def print_sign_outs
    @groups = Group.all

    respond_to do |format|
      format.html
      format.pdf do
      end
      format.xls { response.headers["Content-Disposition"] = "attachment; filename=\"Sign-out-sheets.xml\"" }
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      flash[:success] = "<strong>#{@group.name}</strong> created."
      redirect_to groups_path
    else
      flash.now[:warning] = "somthing went wrong"
      render 'new'
    end
  end

  def edit
   @group = Group.find(params[:id])   
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "<strong>#{@group.name}</strong> was successfully updated"
      redirect_to groups_path
    else
      flash.now[:warning] = "somthing went wrong"
      render 'edit'
    end
  end

  def update_volunteer_assignment #this action is from groups index it should only be called by an ajax request
    @group = Group.find(params[:id])
    
    if Volunteer.update(params[:volunteer_id], leader_id: params[:id])
    # this should render the update_volunter_assignment.js.erb file
    else
      render 'update_volunteer_assignment_error'
    end
  end

  def update_kid_assignment #this action is from groups index it should only be called by an ajax request
    #@kid = Kid.find(params[:id])
    # @group = Group.find(params[:group_id])
    @group = Group.find(params[:id])
    
    if Kid.update(params[:kid_id], group_id: params[:id])
      # this should render the update_kid_assignment.js.erb file
    else
      render 'update_kid_assignment_error'
    end
  end

  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Class removed"
    redirect_to groups_path
  end
end

private

def group_params
  params.require(:group).permit(:name, :grade_id)
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_grades
    ["Pre-K", "4k", "5k", "1st", "2nd", "3rd", "4th", "5th", "6th & 7th"]
  end
end

app/views/groups/_form.html.erb
<div class="form-group row">
  <%= f.label :name, class: "col-sm-1 col-form-label" %>
  <div class="col-sm-10">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

  <div class="form-group row">
    <%= f.label :grade_id, class: "col-sm-1 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :grade_id, group_grades.map.with_index{ |s, i| [s, i]}, {prompt: "Select Grade"}, {class: "form-control custom-select"}  %>
      </div>
  </div>

app/views/groups/_group_index_card.html.erb
<div class=" col-12 col-sm-6 col-xl-4">
  <div id="group_<%= group.id %>" class="groupcard card mb-4"  data-group-id="<%= group.id %>">
    <div class="card-header">
      <ul class="nav nav-pills card-header-pills">
	<li class="nav-item">
	  <%= link_to "Edit", edit_group_path(group.id), class: "nav-link active" %>
	</li>
	<li class="nav-item">
	  <a class="nav-link" href="">Print</a>
	</li>
	<%= link_to "Delete", group_path(group.id), method: :delete, class: "nav-link", data: {confirm: "Are you sure?" } %>
      </ul>
    </div>
    <div class="card-block">
      <h4 class="card-title"><%= group.name_grade %></h4>
      <hr>
      <div class="row teacherrow">
	<%= render partial: "group_leaders_col", locals: {group:group} %>
      </div>
    </div>
    <table id="group_<%= group.id %>_kids_table" class="table table-sm table-hover">
      <%= render partial: "group_kids_table", locals: {group: group} %>
    </table>
  </div>
</div>

app/views/groups/_group_kids_table.html.erb
<tbody class="kids_table_boddy">
  <% group.kids.each do |kid| %>
  <tr onclick="window.location='<%= kid_path(kid)%>';" style='cursor: pointer;'>
    <td></td> <!-- Use this for the buddy request icon -->
    <td><%= "#{kid.first_name} #{kid.last_name}" %></td>
    <td><%#= find_age(kid.birthdate) %></td>
    <td>
      <% if kid.allergies %>
      <span class="badge badge-warning">Allergies</span>
      <% end %>
      <% if kid.medical_issues %>
      <span class="badge badge-info">Other</span>
      <% else %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>

app/views/groups/_group_leaders_col.html.erb
<% group.volunteers.sort_by_last_name.each do |leader| %>
<div class="col-6">
  <%= link_to "#{leader.first_name} #{leader.last_name}", volunteer_path(leader) %>
</div>
<% end %>

app/views/groups/_unassigned_kid.html.erb
<div  id="kids-div" class="tab-pane active" role="tabpanel1">
  <% @unassigned_kids.sort_by_grade.sort_by_last_name.each do | kid | %>
    <div id="kid_<%= kid.id %>" class="kidcard p-2 m-2 bg-primary rounded" data-kid-id="<%= kid.id %>" draggable="true">
      <p><strong><%= kid.full_name %></strong> - <%= kid.grade %> - <%= find_age(kid.birthdate) %> y/o</p>
      <% unless kid.buddy_request.empty? %>
      <p>Buddy: <%= kid.buddy_request %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/groups/_unassigned_teachers.html.erb
<div  id="teachers-div" class="tab-pane" role="tabpanel1">
  <% @unassigned_leaders.sort_by_last_name.each do | teacher | %>
    <div id="teacher_<%= teacher.id %>" class="teachercard p-2 m-2 bg-info rounded" data-volunteer-id="<%= teacher.id %>" draggable="true">
      <p><strong><%= teacher.full_name %></strong></p>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<%= content_for :title do %>
Edit: <%= "#{@group.name_grade}" %>
<% end %>

<div class="container w-50">
  <h1>Edit: <strong><%= "#{@group.name_grade}" %></strong></h1>
  </br>
  <%= form_for @group do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <div class="form-group row">
    <div class="col-sm-10 offset-1">
      <%= f.submit 'Save',  class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>

app/views/groups/groups_sign_outs.xls.erb
<?xml version="1.0" encoding="utf-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="2017 Classes">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Class</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
      </Row>
      <% @groups.sort_by_grade.sort_by_name.each do |group| %>
      <Row>
	<Cell><Data ss:Type="String"><%=group.name %></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
      </Row>
      <Row>
      </Row>
      <% group.kids.sort_by_last_name.each do |kid| %>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.parent_name}" %></Data></Cell>
      </Row>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.pickupper_1_name}" %></Data></Cell>
      </Row>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.pickupper_2_name}" %></Data></Cell>
      </Row>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.pickupper_3_name}" %></Data></Cell>
      </Row>
      <% end %>
      <Row>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/groups/index.html.erb
<div class="container w-100" style="">
  <h1>Classes</h1>
  
  <div class="row mt-4">
    <div class="col-lg-3 mb-3">
      <a class="btn btn-primary btn-sm" href="<%= new_group_path %>">Add New</a>
      <a class="btn btn-secondary btn-sm" href="<%= groups_path(format: :xls)  %>">Excel</a>
      <a class="btn btn-secondary btn-sm" href="<%= print_sign_outs_groups_path(format: :pdf)  %>">Sign-out Sheets</a>
    </div>
  </div>
  <hr>
  <br>
  <div class="w-75 float-left" stlye="height: 80vh; overflow: scroll;">
    <div id="groups-div" class="row">
      <% @groups.sort_by_grade.sort_by_name.each do | group | %>
      <%= render partial: "group_index_card", locals: {group: group} %>
      <% end %>
    </div>
  </div>
  <div class="w-25" style="height: 80vh; right:0; overflow: scroll; position: fixed;">
    <div class=" bg-faded">
      <h4>Unassigned</h4>
      <ul class="nav nav-tabs" role="tablist">
	<li class="nav-item">
	  <a class="nav-link active" data-toggle="tab" href="#kids-div" role="tab">Kids</a>
	</li>
	<li class="nav-item">
	  <a class="nav-link" data-toggle="tab" href="#teachers-div" role="tab">Teachers</a>
	</li>
      </ul>
      <div class="h-100 tab-content">
	<%= render partial: "unassigned_kid", locals: {kids: @unassigned_kids} %>
	<%= render partial: "unassigned_teachers" %>
	<br>
      </div>
    </div>
  </div>
</div>

app/views/groups/index.xls.erb
<?xml version="1.0" encoding="utf-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="2017 Classes">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Class</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Allergies/Medical</Data></Cell>
      </Row>
      <% @groups.sort_by_grade.sort_by_name.each do |group| %>
      <Row>
	<Cell><Data ss:Type="String"><%=group.name %></Data></Cell>
      </Row>
      <% group.volunteers.sort_by_last_name.each do |leader| %>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"><%= "#{leader.first_name} #{leader.last_name}" %></Data></Cell>
      </Row>
      <% end %>
      <Row>
      </Row>
      <% group.kids.sort_by_last_name.each do |kid| %>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.first_name} #{kid.last_name}" %></Data></Cell>
	<% if kid.allergies %>
        <Cell><Data ss:Type="String"><%= "#{kid.allergies_notes}" %></Data></Cell>
	<% end %>
	<% if kid.medical_issues %>
	<Cell><Data ss:Type="String"><%= "#{kid.medical_issues_notes}" %></Data></Cell>
	<% else %>
	<Cell><Data ss:Type="String"> </Data></Cell>
	<% end %>
      </Row>
      <% end %>
      <Row>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/groups/new.html.erb
<%= content_for :title do %>
New Class
<% end %>

<div class="container w-50">
  <%= form_for @group do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <div class="form-group row">
    <div class="col-sm-10 offset-1">
      <%= f.submit 'Save',  class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>

app/views/groups/print_sign_outs.xls.erb
<?xml version="1.0" encoding="utf-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="2017 Classes">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Class</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
      </Row>
      <% @groups.sort_by_grade.sort_by_name.each do |group| %>
      <Row>
	<Cell><Data ss:Type="String"><%=group.name %></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
      </Row>
      <Row>
      </Row>
      <% group.kids.sort_by_last_name.each do |kid| %>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.full_name}" %></Data></Cell>
      </Row>	    
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.parent_name}" %></Data></Cell>
      </Row>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.pickupper_1_name}" %></Data></Cell>
      </Row>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.pickupper_2_name}" %></Data></Cell>
      </Row>
      <Row>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= "#{kid.pickupper_3_name}" %></Data></Cell>
      </Row>
      <% end %>
      <Row>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/groups/update_volunteer_assignment.js.erb
<%=render partial: "group_leaders_col", locals: {group: @group} %>