config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  
  # Recreates the Devise registrations routes
  # They act on a singular user (the signed in user)
  # Add the actions you want in 'only:'
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
      get 'cancel'
    end
  end

    authenticated :user do   
      # Seting up admin scope for :users
      # so as to not conflict with the routes from devise.
      # These routes should give users with the admin role
      # the abbility to edit info for all other users.
      scope "/admin" do
        resources :users do
        end
      end
      
      resources :volunteers do
      end
    
      resources :groups do
        # member do
        #   get 'print'
        # end
        collection do
          post 'update_kid_assignment'
          post 'update_volunteer_assignment'
          get 'print_sign_outs'
        end
      end
      
      resources :kids do
        get 'register', on: :new
        collection do
          post 'confirm'
          get 'print_all_kids'
        end
      end

      resources :locations do
        collection do
          post 'update_volunteer_assignment'
        end
      end

      root to: 'kids#index', as: :authenticated_root
    end
  

    root to: redirect('users/sign_in')
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= sanitize(value) %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand text-white">VBS Registration</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav mr-auto">
	  <li class="nav-item">
	    <%= link_to "Kids", kids_path, class: "nav-link" %>
	  </li>
	  <li class="nav-item">
            <%= link_to "Classes", groups_path, class: "nav-link" %>
	  </li>
	  <li class="nav-item">
           <%= link_to "Stations", locations_path, class: "nav-link" %>
	  </li>
	  <li class="nav-item">
	    <%= link_to "Volunteers", volunteers_path, class: "nav-link" %>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="#">Dashboard</a>
	  </li>
	  <% if current_user.try(:admin?) %>
	  <li class="nav-item dropdown">
	    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	      Admin
	    </a>
	    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Edit Users", users_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
	    </div>
	    </li>
	  <% else %>
	  <li class="nav-item">
             <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
	  </li>
	  <% end %>
	</ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" style="">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %><%= action_name %>" style="">
    <%= render "layouts/header" %>
    <%= render partial: "layouts/flash_messages", locals: {flash: flash} %>
    <%= yield %>
  </body>
</html>

app/views/layouts/public-authentication.html.erb
<!DOCTYPE html>
<html lang="en" style="height: 100%">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="height:100%; background-color: rgba(214,214,214,0.6);">
    <div class="container d-flex h-100 w-100">
      <div class="row w-100 my-auto">
	<div class="col-lg-4 mx-auto">
	  <div class="card">
	    <div class="card-block">
	      <%= yield %>
	    </div>
	  </div>
	</div> 
      </div>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>